exports.API_TYPES = {
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  PASSPORT: 'PASSPORT',
  AADHAAR_COMPREHENSIVE: 'AADHAARCOMPREHENSIVE',
  AADHAAR_COMPREHENSIVE_OTP_VALIDATE: 'AADHAARCOMPREHENSIVEOTPVALIDATE',
  DRIVING_LICENSE: 'DRIVINGLICENSE',
  RC_TEXT: 'RCTEXT',
  VOTER: 'VOTER'
}
