// src/constants/apiTypes.js
exports.DOCUMENT_TYPES = {
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  PASSPORT: 'PASSPORT',
  AADHAAR_COMPREHENSIVE: 'AADHAARCOMPREHENSIVE',
  AADHAAR_COMPREHENSIVE_OTP_VALIDATE: 'AADHAARCOMPREHENSIVEOTPVALIDATE',
  DRIVING_LICENSE: 'DRIVING_LICENSE',
  RCTEXT: 'RCTEXT'
}
